### ISSUE TITLE
deal.II publications Thomas Wick

### ISSUE THREAD

**Issue by tommeswick** [dealii/publication-list#283]
@book{Wi20_book,
      author = "Thomas Wick",
      title = "Multiphysics Phase-Field Fracture: Modeling, Adaptive Discretizations, and Solvers",
      year = "2020",
      publisher = "De Gruyter",
      address = "Berlin, Boston",
      isbn = "978-3-11-049739-7",
      doi = "https://doi.org/10.1515/9783110497397",
      url = "https://www.degruyter.com/view/title/523232"
}

@unpublished{FaYiWi21_EWCO,
   author = {M. Fan and Y. Jin and T. Wick},
   title = {A quasi-monolithic phase-field description for mixed-mode fracture using predictor-corrector mesh adaptivity},
note = {Engineering with Computers (EWCO), accepted for publication},
year = {2021}
}

@unpublished{Wi21_CMAM,
   author = {T. Wick},
   title = {Dual-weighted residual a posteriori error estimates for a penalized phase-field slit discontinuity problem},
note = {Computational Methods in Applied Mathematics (CMAM), accepted for publication},
year = {2021}
}

@article{FrRiWi21_LocModFE,
title = {LocModFE: Locally modified finite elements for approximating interface problems in deal.II},
journal = {Software Impacts},
volume = {8},
pages = {100070},
year = {2021},
issn = {2665-9638},
doi = {https://doi.org/10.1016/j.simpa.2021.100070},
url = {https://www.sciencedirect.com/science/article/pii/S266596382100018X},
author = {Stefan Frei and Thomas Richter and Thomas Wick},
keywords = {Locally modified finite elements, Fitted finite elements, Interface problems, , Deal.II},
abstract = {We describe the Software package LocModFE, which is an implementation of a locally modified finite element method for an accurate solution of interface problems. The code was originally developed in the finite element library Gascoigne 3d and has now been rewritten in the widerspread library deal.II. This makes the concept of locally modified finite elements accessible to many users all over the world. Applications range from simple Poisson interface problems over multi-phase flows to complex multi-physics problems, such as fluid–structure interactions. Being based on deal.II, it provides plenty of possibilities for future extensions, e.g., parallel computing, multigrid solvers or mesh adaptivity.}
}

@article{EndtLaWi20_smart,
author = {Bernhard Endtmayer and Ulrich Langer and Thomas Wick},
doi = {doi:10.1515/cmam-2020-0036},
url = {https://doi.org/10.1515/cmam-2020-0036},
title = {Reliability and Efficiency of DWR-Type A Posteriori Error Estimates with Smart Sensitivity Weight Recovering},
journal = {Computational Methods in Applied Mathematics},
volume = {21},
number = {2},
year = {2021}
}

@article{HeiWi20,
title = "pfm-cracks: A parallel-adaptive framework for phase-field fracture propagation",
journal = "Software Impacts",
volume = "6",
pages = "100045",
year = "2020",
issn = "2665-9638",
doi = "https://doi.org/10.1016/j.simpa.2020.100045",
url = "http://www.sciencedirect.com/science/article/pii/S2665963820300361",
author = "Timo Heister and Thomas Wick",
keywords = "Phase-field fracture, Parallel computing, Primal–dual active set, Semi-smooth Newton, Adaptivity, Open-source software",
abstract = "This paper describes the main features of our parallel-adaptive open-source framework for solving phase-field fracture problems called pfm-cracks. Our program allows for dimension-independent programming in two- and three-dimensional settings. A quasi-monolithic formulation for the coupled two-component system of displacements and a phase-field indicator variable is used. The nonlinear problem is solved with a robust, efficient semi-smooth Newton algorithm. A highlight is adaptive predictor–corrector mesh refinement. The code is fully parallelized and scales to 1000 and more MPI ranks. Illustrative tests demonstrate the current capabilities, from which some are parts of benchmark collections."
}

@article{JaWheWi21,
title = {A phase-field multirate scheme with stabilized iterative coupling for pressure driven fracture propagation in porous media},
journal = {Computers & Mathematics with Applications},
volume = {91},
pages = {176-191},
year = {2021},
note = {Robust and Reliable Finite Element Methods in Poromechanics},
issn = {0898-1221},
doi = {https://doi.org/10.1016/j.camwa.2020.11.009},
url = {https://www.sciencedirect.com/science/article/pii/S089812212030434X},
author = {Mohamad Jammoul and Mary F. Wheeler and Thomas Wick},
keywords = {Phase-field fracture, Porous media, Multirate, Iterative coupling, Benchmarks},
abstract = {Phase-field methods have the potential to simulate large scale evolution of networks of fractures in porous media without the need to explicitly track interfaces. Practical field simulations require however that robust and efficient decoupling techniques can be applied for solving these complex systems. In this work, we focus on the mechanics-step that involves the coupling of elasticity and the phase-field variable. We develop a multirate scheme in which a coarser time grid is employed for the mechanics equation (i.e., the displacements) and a finer time grid is taken for the phase-field problem. The performance of this algorithm is demonstrated for two test cases.}
}

// Please update with existing arXiv entry already available on publication list
@article{JoLaWi20,
title = "Matrix-free multigrid solvers for phase-field fracture problems",
journal = "Computer Methods in Applied Mechanics and Engineering",
volume = "372",
pages = "113431",
year = "2020",
issn = "0045-7825",
doi = "https://doi.org/10.1016/j.cma.2020.113431",
url = "http://www.sciencedirect.com/science/article/pii/S0045782520306162",
author = "D. Jodlbauer and U. Langer and T. Wick",
keywords = "Phase-field fracture propagation, Matrix-free, Geometric multigrid, Primal–dual active set",
abstract = "In this work, we present a framework for the matrix-free solution to a monolithic quasi-static phase-field fracture model with geometric multigrid methods. Using a standard matrix-based approach within the Finite Element Method requires lots of memory, which eventually becomes a serious bottleneck. A matrix-free approach overcomes this problem and greatly reduces the amount of required memory, allowing to solve larger problems on available hardware. One key challenge is concerned with the crack irreversibility for which a primal–dual active set method is employed. Here, the active set values of fine meshes must be available on coarser levels of the multigrid algorithm. The developed multigrid method provides a preconditioner for a generalized minimal residual (GMRES) solver. This method is used for solving the linear equations inside Newton’s method for treating the overall nonlinear-monolithic discrete displacement/phase-field formulation. Several numerical examples demonstrate the performance and robustness of our solution technology. Mesh refinement studies, variations in the phase-field regularization parameter, iterations numbers of the linear and nonlinear solvers, and some parallel performances are conducted to substantiate the efficiency of the proposed solver for single fractures, multiple pressurized fractures, and a L-shaped panel test in three dimensions."
}

@article{JoLaWi20_parallel,
author = {Jodlbauer, D. and Langer, U. and Wick, T.},
title = {Parallel Matrix-Free Higher-Order Finite Element Solvers for Phase-Field Fracture Problems},
journal = {Mathematical and Computational Applications},
volume = {25},
number = {3},
pages = {40},
year = {2020}
}

@article{WheWiLee20,
title = {{IPACS: Integrated Phase-Field Advanced Crack Propagation Simulator. An adaptive, parallel, physics-based-discretization phase-field framework for fracture propagation in porous media}},
journal = "Computer Methods in Applied Mechanics and Engineering",
volume = "367",
pages = "113124",
year = "2020",
issn = "0045-7825",
doi = "https://doi.org/10.1016/j.cma.2020.113124",
url = "http://www.sciencedirect.com/science/article/pii/S0045782520303091",
author = "Mary F. Wheeler and Thomas Wick and Sanghyun Lee",
keywords = "Phase-field fracture, Porous media, Computer implementation, Numerical simulations, Handbook, IPACS",
abstract = "In this work, we review and describe our computational framework for solving multiphysics phase-field fracture problems in porous media. Therein, the following five coupled nonlinear physical models are addressed: displacements (geo-mechanics), a phase-field variable to indicate the fracture position, a pressure equation (to describe flow), a proppant concentration equation, and/or a saturation equation for two-phase fracture flow, and finally a finite element crack width problem. The overall coupled problem is solved with a staggered solution approach, known in subsurface modeling as the fixed-stress iteration. A main focus is on physics-based discretizations. Galerkin finite elements are employed for the displacement-phase-field system and the crack width problem. Enriched Galerkin formulations are used for the pressure equation. Further enrichments using entropy-vanishing viscosity are employed for the proppant and/or saturation equations. A robust and efficient quasi-monolithic semi-smooth Newton solver, local mesh adaptivity, and parallel implementations allow for competitive timings in terms of the computational cost. Our framework can treat two- and three-dimensional realistic field and laboratory examples. The resulting program is an in-house code named IPACS (Integrated Phase-field Advanced Crack Propagation Simulator) and is based on the finite element library deal.II. Representative numerical examples are included in this document."
}

// Please update with existing arXiv entry already available on publication list
@article{WiWo20,
author = {Wick, Thomas and Wollner, Winnifried},
title = {Optimization with nonstationary, nonlinear monolithic fluid-structure interaction},
journal = {International Journal for Numerical Methods in Engineering},
year = {2020},
volume = {n/a},
number = {n/a},
pages = {},
keywords = {gradient-based optimization, monolithic formulation, optimal control, optimal design, unsteady nonlinear fluid-structure interaction},
doi = {10.1002/nme.6372},
url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.6372},
eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/nme.6372},
abstract = {Summary Within this work, we consider optimization settings for nonlinear, nonstationary fluid-structure interaction (FSI). The problem is formulated in a monolithic fashion using the arbitrary Lagrangian-Eulerian framework to set-up the fluid-structure forward problem. In the optimization approach, either optimal control or optimal design problems are treated. In the latter, the stiffness of the solid is estimated from given reference values. In the numerical solution, the optimization problem is solved with a gradient-based solution algorithm. The nonlinear subproblems of the FSI forward problem are solved with a Newton method including line search. Specifically, we will formally provide the backward-in-time running adjoint state used for gradient computations. Our algorithmic developments are demonstrated with some numerical examples as, for instance, extensions of the well-known fluid-structure benchmark settings and a flapping membrane test in a channel flow with elastic walls.}
}

@misc{BaMaWaWiWo20,
   author = {Seshadri Basava and Katrin Mang and Mirjam Walloth and Thomas
  Wick and Winnifried Wollner},
   title = {Adaptive and Pressure-Robust Discretization of Incompressible Pressure-Driven Phase-Field Fracture},
   howpublished = {DFG-SPP 1748 final report, book article, accepted},
   year = {2020}
}

@misc{MaWi21,
   author = {K. Mang and T. Wick},
   title = {Numerical Studies of Different Mixed Phase-Field Fracture Models for Simulating Crack Propagation in Punctured EPDM Strips},
   howpublished = {WCCM-ECCOMAS2020},
   year = {2021},
   url = {https://www.scipedia.com/public/Mang_Wick_2021a}
}

@misc{mang2021mixed,
      title={A mixed phase-field fracture model for crack propagation in punctured EPDM strips}, 
      author={Katrin Mang and Andreas Fehse and Nils Hendrik Kröger and Thomas Wick},
      year={2021},
      eprint={2104.14826},
      archivePrefix={arXiv},
      primaryClass={math.NA}
}

@misc{Wi21_WCCM,
   author = {T. Wick},
   title = {On the Adjoint Equation in Fluid-Structure Interaction},
   howpublished = {WCCM-ECCOMAS2020},
   year = {2021},
   url = {https://www.scipedia.com/public/Wick_2021}
}

@article{FeKroeMaWi21_PAMM,
author = {Fehse, Andreas and Kröger, Nils Hendrik and Mang, Katrin and Wick, Thomas},
title = {Crack path comparisons of a mixed phase-field fracture model and experiments in punctured EPDM strips},
journal = {PAMM},
volume = {20},
number = {1},
pages = {e202000335},
doi = {https://doi.org/10.1002/pamm.202000335},
url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/pamm.202000335},
eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/pamm.202000335},
abstract = {Abstract Working on quasi-static phase-field fracture modeling in nearly incompressible solids for crack propagation is a challenging task. To avoid arising locking effects therein, a mixed form for the solid displacement equation is developed, resulting in two unknowns: a displacement field and a hydro-static pressure variable. In order to fulfil an inf-sup condition, stable Taylor-Hood elements are employed for the displacement-pressure system. The irreversibility condition of the crack evolution is handled by help of a primal-dual active set method. To get both a sharper crack and reasonable computational costs, adaptive meshes are used based on a predictor-corrector scheme. The crack paths from the numerical simulations are compared on the experimentally observed crack paths in carbon black filled ethylene propylene diene monomer (EPDM) rubber strips. The punctured EPDM strips with a hole and a given notch at different heights are stretched till total failure.},
year = {2021}
}

@article{EndtLaNeiWiWo19_PAMM,
author = {Endtmayer, Bernhard and Langer, Ulrich and Neitzel, Ira and Wick, Thomas and Wollner, Winnifried},
title = {Mesh adaptivity and error estimates applied to a regularized p-Laplacian constrainted optimal control problem for multiple quantities of interest},
journal = {PAMM},
volume = {19},
number = {1},
pages = {e201900231},
doi = {https://doi.org/10.1002/pamm.201900231},
url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/pamm.201900231},
eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/pamm.201900231},
abstract = {Abstract In this work, we derive goal-oriented error estimates and mesh adaptivity for multiple quantities of interest for optimal control problems with the regularized p-Laplace equation as constraint. We apply the dual-weighted residual method to the reduced formulation, and combine several quantities of interest. Finally, we present a numerical example with p = 10.},
year = {2019}
}

// Please update with existing arXiv entry already available on publication list
@article{EndtNeiLaWiWo20,
title = "Multigoal-oriented optimal control problems with nonlinear PDE constraints",
journal = "Computers {\&} Mathematics with Applications",
volume = "79",
number = "10",
pages = "3001 - 3026",
year = "2020",
issn = "0898-1221",
doi = "https://doi.org/10.1016/j.camwa.2020.01.005",
url = "http://www.sciencedirect.com/science/article/pii/S0898122120300122",
author = "B. Endtmayer and U. Langer and I. Neitzel and T. Wick and W. Wollner",
keywords = "Optimal control, Multigoal-oriented a posteriori error estimation, Regularized -Laplacian, Dual-weighted residuals, Finite elements",
abstract = "In this work, we consider an optimal control problem subject to a nonlinear PDE constraint and apply it to a semi-linear monotone PDE and the regularized p-Laplace equation. To this end, a reduced unconstrained optimization problem in terms of the control variable is formulated. Based on the reduced approach, we then derive an a posteriori error representation and mesh adaptivity for multiple quantities of interest. All quantities are combined to one, and then the dual-weighted residual (DWR) method is applied to this combined functional. Furthermore, the estimator allows for balancing the discretization error and the nonlinear iteration error. These developments allow us to formulate an adaptive solution strategy, which is finally substantiated with the help of several numerical examples."
}

**Comment by marcfehling** [comment]
I'm preparing a patch for these entries right now. All articles but the following are already in the publication list:

> @misc{BaMaWaWiWo20,
> author = {Seshadri Basava and Katrin Mang and Mirjam Walloth and Thomas
> Wick and Winnifried Wollner},
> title = {Adaptive and Pressure-Robust Discretization of Incompressible Pressure-Driven Phase-Field Fracture},
> howpublished = {DFG-SPP 1748 final report, book article, accepted},
> year = {2020}
> }

Do you have a link or doi to this particular resource? All I could find is an article on arxiv that matches this description: https://arxiv.org/abs/2006.16566

**Comment by marcfehling** [comment]
In fact, just as I wrote these lines, I found it in the list of 2022 publications: https://github.com/dealii/publication-list/blob/9015e05dbc45ad623d407f1232d9a3c6b4a68120/publications-2022.bib#L68-L76

So all entries are already part of our publication list. Thank you for reporting!
