### ISSUE TITLE
iHeart

### ISSUE THREAD

**Issue by drwells** [dealii/publication-list#379]
Quarteroni's group has been publishing a ton of papers using iHeart (which uses deal.II). Here's a recent one:

https://arxiv.org/pdf/2208.09435.pdf (EDIT: now part of the publication list)

I think we only have three of these in the repository so far.

**Comment by peterrum** [comment]
@elauksap Could one of you take over? Thanks!

**Comment by marcfehling** [comment]
Another iheart publication, currently in 'in press' stage: https://www.sciencedirect.com/science/article/pii/S0010482522008514

**Comment by bangerth** [comment]
We've got 17 Quarteroni papers in the 2022 list, which must surely be quite close to the total. This includes the one arXiv preprint explicitly linked to above. So let me close this.
