### ISSUE TITLE
New items

### ISSUE THREAD

**Issue by agrayver** [dealii/publication-list#527]
Dear all
some further input from geosciences:

@article{dambly2023insights,
author = {Dambly, M. L. T. and Samrock, F. and Grayver, A. V. and Saar, M. O.},
title = {Insights on the Interplay of Rifting, Transcrustal Magmatism and Formation of Geothermal Resources in the Central Segment of the Ethiopian Rift Revealed by 3-D Magnetotelluric Imaging},
journal = {Journal of Geophysical Research: Solid Earth},
volume = {128},
number = {7},
pages = {e2022JB025849},
doi = {https://doi.org/10.1029/2022JB025849},
year = {2023}
}

@article{samrock2023geophysically,
  title={Geophysically guided well siting at the Aluto-Langano geothermal reservoir},
  author={Samrock, Friedemann and Grayver, Alexander and Dambly, Marie Luise Texas and M{\"u}ller, Madeleine R and Saar, Martin},
  journal={Geophysics},
  volume={88},
  number={5},
  pages={1--43},
  year={2023},
  publisher={Society of Exploration Geophysicists}
}

Some more fun. The deal.II-enabled VTU model files were imported into Blender and used to create nice illustrations below. 

![Aluto](https://github.com/dealii/publication-list/assets/8438035/85da3b33-7b4a-4443-8c7e-8001eed1d7cd)

**Comment by marcfehling** [comment]
These articles should also be part of the aspect publication list https://github.com/geodynamics/aspect/issues/2831

**Comment by agrayver** [comment]
To clarify, we have not used ASPECT. We actually imaged the subsurface physicsal properties (electrical conductivity in this case) using real geophysical observations.
