### ISSUE TITLE
Add publications by Mustafa Ağgül

### ISSUE THREAD

**Issue by bangerth** [dealii/publication-list#531]
By email, I received the following list of publications not currently on the website but that use deal.II:

Missing Publications
1. M. Aggul, F. G. Eroglu, S. Kaya, A. Labovsky, A projection based variational multiscale method for a fluid-fluid interaction problem, Computer Methods in Applied Mechanics and Engineering, vol.365, 112957, 2020.
https://doi.org/10.1016/j.cma.2020.112957
2. M. Aggul, S. Kaya, Defect-Deferred Correction Method Based on a Subgrid Artificial Viscosity Modeling for Fluid-Fluid Interaction, Applied Numerical Mathematics, vol.160, 178-191, 2021.
https://doi.org/10.1016/j.apnum.2020.10.004
3. M. Aggul, Defect Deferred Correction Method Based on a Subgrid Artificial Viscosity Modeling, Journal of Mathematical Analysis and Applications, vol.497(2), 124878, 2021.
https://doi.org/10.1016/j.apnum.2020.10.004
4. M. Aggul, A Grad-Div Stabilized Penalty Projection Algorithm for Fluid-Fluid Interaction Problem, Applied Mathematics and Computation, vol.414, 126670, 2022.
https://doi.org/10.1016/j.amc.2021.126670
5. M. Aggul, A. Labovsky, Approximate Deconvolution Models for a Fluid-Fluid Interaction Problem with High Reynolds Numbers, Computers & Mathematics with Applications, vol.117, 113-126, 2022.
https://doi.org/10.1016/j.camwa.2022.04.011
6. M. Aggul, F. G. Eroglu, S. Kaya, Artificial Compression Method for MHD System in Elsässer Variables, Applied Numerical Mathematics, 185: 72-87, 2022. 
https://doi.org/10.1016/j.apnum.2022.11.009
7. M. Aggul, A. Labovsky, E. Onal, K. Schwiebert, Fluid-Fluid Interaction Problems at High Reynolds Numbers: Reducing the Modeling Error with LES-C, SIAM Journal on Numerical Analysis, vol.61, iss.2, pp. 707-732, 2023.
https://doi.org/10.1137/22M1494269
8. M. Aggul, A. B. Cibik, Fatma G. Eroglu, S. Kaya, Deferred Correction Method for the Continuous Data Assimilation Model, Computer Methods in Applied Mechanics, and Engineering, vol.415, 116259, 2023.
https://doi.org/10.1016/j.cma.2023.116259

Missing Thesis

A High Accuracy Minimally Invasive Regularization Technique for Navier-Stokes Equations at High Reynolds Numbers, Michigan Tech, 2016.

**Comment by marcfehling** [comment]
Articles 1,2,3 and the master's thesis do not explicitly refer to deal.II. But since the author states this is the case, we should add all of them. I will prepare a patch.
