### ISSUE TITLE
Some other publications

### ISSUE THREAD

**Issue by bangerth** [dealii/publication-list#63]

**Comment by bangerth** [comment]
Ah, hit enter too early. What I wanted to say is that here are a few other publications I know of:

*    E.C. Bryant, W.C. Sun, Mixed-mode phase field fracture for secondary cracks in isotropic and anisotropic brittle rocks with consistent kinematics, Computer Methods in Applied Mechanics and Engineering, 342:561-584, doi:10.1016/j.cma.2018.08.008, 2018. 
*    S. Na, W.C. Sun, Computational thermomechanics of crystalline rock. Part I: a combined multi-phase-field/crystal plasticity approach for single crystal simulations, Computer Methods in Applied Mechanics and Engineering, 338:657-691, doi:10.1016/j.cma.2017.12.022, 2018. 
*    J. Choo", W.C. Sun, Coupled phase-field and plasticity modeling of geological materials: From brittle fracture to ductile flow,  Computer Methods in Applied Mechanics and Engineering, 330:1-32, doi:10.1016/j.cma.2017.10.009, 2018. 
*    J. Choo", W.C. Sun, Cracking and damage from crystallization in pores: Coupled chemo-poro-mechanics and phase-field modeling, Computer Methods in Applied Mechanics and Engineering, 335:347-379, doi:10.1016/j.cma.2018.01.044, 2018. 
*    S. Na, W.C. Sun, Computational thermo-hydro-mechanics for multiphase freezing and thawing porous media in the finite deformation range, Computer Methods in Applied Mechanics and Engineering, 318:667-700, doi:10.1016/j.cma.2017.01.028, 2017. 

I might get the bibtex files for these, but in case I don't at least I've got it recorded.

**Comment by jppelteret** [comment]
> J. Choo", W.C. Sun, Cracking and damage from crystallization in pores: Coupled chemo-poro-mechanics and phase-field modeling, Computer Methods in Applied Mechanics and Engineering, 335:347-379, doi:10.1016/j.cma.2018.01.044, 2018.
S. Na, W.C. Sun, Computational thermo-hydro-mechanics for multiphase freezing and thawing porous media in the finite deformation range, Computer Methods in Applied Mechanics and Engineering, 318:667-700, doi:10.1016/j.cma.2017.01.028, 2017.

These are duplicates, but the other 3 entries are unique.
