### ISSUE TITLE
Some more publications

### ISSUE THREAD

**Issue by bangerth** [dealii/publication-list#79]
In case anyone wants to take care of those:

  | arXiv:1903.02799
-- | --

**Comment by bangerth** [comment]
Hm, this doesn't show as I want it to... I can't seem to copy paste straight here, so via a detour this is what I have:

1a. S. Frei, T. Richter, T. Wick; An implementation of a locally modified finite element method for interface problems in deal.II, zenodo, October 2018
https://zenodo.org/record/1457758#.XJVJg59IkWN

1b. S. Frei, T. Richter, T. Wick, On the implementation of a locally modified finite element method for interface problems in deal.II, 2018, arXiv

	arXiv:1806.00999

2. T. Wick; Zielorientierte Numerik für Multiphysiksimulationen,
GAMM-Rundbrief, Nr. 2, 2018 (in german)
https://www.gamm-ev.de/images/publikationen/pdf/RB_2018_2.pdf


3. C. J. van Duijn, A. Mikelic, M.F. Wheeler, T. Wick; Thermoporoelasticity via homogenization I. Modeling and formal two-scale expansions,
International Journal of Engineering Science (IJES),
Vol. 138 (2019), pp. 1-25

---> bitte den Preprint aus 2018 entsprechend updaten! Dies ist
    die publizierte Version


4. T. Wick, W. Wollner; On the differentiability of stationary fluid-structure interaction problems with respect to the problem data,
Journal of Mathematical Fluid Mechanics (JMFM),
accepted in Dec 2018

---> bitte den Preprint aus dem Jahr 2014 entsprechend updaten!


5. A. Mikelic, M.F. Wheeler, T. Wick; Phase-field modeling
through iterative splitting of hydraulic fractures in a poroelastic medium,
GEM - International Journal on Geomathematics,
accepted in Oct 2018


6. D. Jodlbauer, U. Langer, T. Wick; Parallel Block-Preconditioned Monolithic Solvers for Fluid-Structure-Interaction Problems,
International Journal for Numerical Methods in Engineering, Vol. 117 (6), 2019, pp. 623-643

---> bitte den Preprint aus 2018 updaten!


7. C.J. van Duijn, A. Mikelic, T. Wick; A monolithic phase-field model of a fluid-driven fracture in a nonlinear poroelastic medium,
Mathematics and Mechanics of Solids,
First published online, Oct 2018


8. S. Lee, A. Mikelic, M. F. Wheeler, T. Wick; Phase-field modeling of two phase fluid filled fractures in a poroelastic medium,
SIAM Multiscale Modeling and Simulation (MMS),
Vol. 16 (4), 2018, pp. 1542-1580



9. B. Endtmayer, U. Langer, T. Wick; Multigoal-Oriented Error Estimates for Non-linear Problems,
Journal of Numerical Mathematics (JNUM), accepted in July 2018

---> ist nun akzeptiert. Finale Bibliography fehlt aber noch.


10. S. Frei, T. Richter, T. Wick; Long-term simulation of large deformation, mechano-chemical FSI in ALE and fully Eulerian coordinates,
Oberwolfach report, No. 39, 2018


11. B. Endtmayer, U. Langer, T. Wick; Multiple goal-oriented error estimates applied to 3D non-linear problems,
PAMM, 2018
https://onlinelibrary.wiley.com/doi/10.1002/pamm.201800048


12. Mats Kirkesæther Brun, Thomas Wick, Inga Berre, Jan Martin Nordbotten, Florin Adrian Radu
An iterative staggered scheme for phase field brittle fracture propagation with stabilizing parameters; 2019, arXiv arXiv:1903.08717


13. Bernhard Endtmayer, Ulrich Langer, Ira Neitzel, Winnifried Wollner, Thomas Wick
Multigoal-oriented optimal control problems with nonlinear PDE constraints; 2019,
arXiv

	arXiv:1903.02799


14. Daniel Jodlbauer, Ulrich Langer, Thomas Wick
Matrix-free multigrid solvers for phase-field fracture problems, 2019,
arXiv

	arXiv:1902.08112


15. Katrin Mang, Thomas Wick, Winnifried Wollner
A phase-field model for fractures in incompressible solids, 2019,
arXiv

	arXiv:1901.05378



16. Bernhard Endtmayer, Ulrich Langer, Thomas Wick
 Two-side a posteriori error estimates for the DWR method, 2018,
arXiv

	arXiv:1811.07586

**Comment by bangerth** [comment]
Also this:

17. Ira Neitzel, Thomas Wick, Winnifried Wollner: An Optimal Control Problem Governed by a Regularized Phase-field Fracture Propagation Model. Part II The Regularization Limit (SPP1962-091, 10/2018, [bib])

**Comment by marcfehling** [comment]
I went through all the articles. A few weren't in the publication list yet. With the new feature I've added preprints to the exisiting articles.

The only entry I didn't add is the software reference, as they describe their use in the article
> 1a. S. Frei, T. Richter, T. Wick; An implementation of a locally modified finite element method for interface problems in deal.II, zenodo, October 2018
> https://zenodo.org/record/1457758#.XJVJg59IkWN
