### ISSUE TITLE
More publications

### ISSUE THREAD

**Issue by bangerth** [dealii/publication-list#90]
1. S. Shiozawa*, S. Lee, M.F. Wheeler 
The effect of stress boundary conditions on fluid-driven fracture propagation in porous media using a phase field modeling approach, 
2019, International Journal for Numerical and Analytical Methods in Geomechanics, DOI: 10.1002/nag.2899	

2. J.Choo*, S. Lee 
Enriched Galerkin Finite Element Method for Locally Mass Conservative Simulation of Coupled Hydromechanical Problems 
2018, Proceedings of China-Europe Conference on Geotehcnical Engineering, Springer Nature Switzerland AG

3. J. Choo*, S.Lee  
Enriched Galerkin finite elements for coupled poromechanics with local mass conservation, 
2018 November, Volume 341, Pages 311-332 Computer Methods in Applied Mechanics and Engineering

4. S. Lee*, M. F. Wheeler 
Enriched Galerkin approximations for two phase flow in porous media with capillary pressure, 
2018, Volume 367, 15 August 2018, Pages 65-86, https://doi.org/10.1016/j.jcp.2018.03.031, Journal of Computational Physics

5. S. Lee*, A. Mikelic, M. F. Wheeler, T. Wick
Phase-field modeling of two phase fluid-filled fractures in a poroelastic medium, 
2018, 16-4, pp. 1542-1580, https://doi.org/10.1137/17M1145239,  SIAM Multiscale Modeling and Simulation

6. S. Lee, B. Min*, M. F. Wheeler 
Optimal hydraulic fracturing design using the phase field model coupled with global-objective genetic algorithm, 
2018, Volume 22, Issue 3, pp 833-849, Computational Geosciences, doi:10.1007/s10596-018-9728-6

7. Rencheng Dong*, M.F. Wheeler, S. Lee 
Numerical Simulation of Matrix Acidizing in Fractured Carbonate Reservoirs Using Adaptive Enriched Galerkin Method 
2019, SPE-193862-MS, SPE RSC 2019, https://doi.org/10.2118/193862-MS

8. M.F. Wheeler*, S. Srinivasan, S. Lee, M. Singh 
Unconventional Reservoir Management Modeling Coupling Diffusive Zone/Phase Field Fracture Modeling and Fracture Probability Maps,  
2019, SPE 193830-MS, SPE RSC 2019, https://doi.org/10.2118/193830-MS
			
3. W. Choi, S. Lee*  
Optimal Error Estimate of Elliptic Problems with Dirac Sources,  
2019, submitted

Ah, here is the bibtex

@inproceedings{dong2019numerical,
  title={Numerical Simulation of Matrix Acidizing in Fractured Carbonate Reservoirs Using Adaptive Enriched Galerkin Method},
  author={Dong, Rencheng and Lee, Sanghyun and Wheeler, Mary and others},
  booktitle={SPE Reservoir Simulation Conference},
  year={2019},
  organization={Society of Petroleum Engineers}
}

@inproceedings{wheeler2019unconventional,
  title={Unconventional Reservoir Management Modeling Coupling Diffusive Zone/Phase Field Fracture Modeling and Fracture Probability Maps},
  author={Wheeler, Mary F and Srinivasan, Sanjay and Lee, Sanghyun and Singh, Manik and others},
  booktitle={SPE Reservoir Simulation Conference},
  year={2019},
  organization={Society of Petroleum Engineers}
}

@article{doi:10.1002/nag.2899,
author = {Shiozawa, Sogo and Lee, Sanghyun and Wheeler, Mary F.},
title = {The effect of stress boundary conditions on fluid-driven fracture propagation in porous media using a phase-field modeling approach},
journal = {International Journal for Numerical and Analytical Methods in Geomechanics},
volume = {43},
year = {2019},
number = {6},
pages = {1316-1340},
keywords = {fluid-driven fracture, phase field, porous media, stress boundary conditions},
doi = {10.1002/nag.2899},
url = {https://onlinelibrary.wiley.com/doi/abs/10.1002/nag.2899},
eprint = {https://onlinelibrary.wiley.com/doi/pdf/10.1002/nag.2899},
abstract = {Summary A phase-field approach for fluid-driven fracture propagation in porous media with varying constant compatible stress boundary conditions is discussed and implemented. Since crack opening displacement, fracture path, and stress values near the fracture are highly dependent on the given boundary conditions, it is crucial to take into account the impact of in situ stresses on fracturing propagation for realistic applications. We illustrate several numerical examples that include the effects of different boundary conditions on the fracture propagation. In addition, an example using realistic boundary conditions from a reservoir simulator is included to show the capabilities of our computational framework.}
}
@article{choo2018enriched,
  title={Enriched Galerkin finite elements for coupled poromechanics with local mass conservation},
  author={Choo, Jinhyun and Lee, Sanghyun},
  journal={Computer Methods in Applied Mechanics and Engineering},
  volume={341},
  pages={311--332},
  year={2018}
}

@inproceedings{choo2018enriched,
  title={Enriched Galerkin Finite Element Method for Locally Mass Conservative Simulation of Coupled Hydromechanical Problems},
  author={Choo, Jinhyun and Lee, Sanghyun},
  booktitle={Proceedings of China-Europe Conference on Geotechnical Engineering},
  pages={312--315},
  year={2018},
  organization={Springer}
}

@article{lee2018enriched,
  title={Enriched Galerkin methods for two-phase flow in porous media with capillary pressure},
  author={Lee, Sanghyun and Wheeler, Mary F},
  journal={Journal of Computational Physics},
  volume={367},
  pages={65--86},
  year={2018},
  publisher={Elsevier}
}

@article{lee2018optimal,
  title={Optimal design of hydraulic fracturing in porous media using the phase field fracture model coupled with genetic algorithm},
  author={Lee, Sanghyun and Min, Baehyun and Wheeler, Mary F},
  journal={Computational Geosciences},
  volume={22},
  number={3},
  pages={833--849},
  year={2018},
  publisher={Springer International Publishing}
}

@article{lee2018phase,
  title={Phase-field modeling of two phase fluid filled fractures in a poroelastic medium},
  author={Lee, Sanghyun and Mikelic, Andro and Wheeler, Mary F and Wick, Thomas},
  journal={Multiscale Modeling \& Simulation},
  volume={16},
  number={4},
  pages={1542--1580},
  year={2018},
  publisher={Society for Industrial and Applied Mathematics}
}

**Comment by genevaporter** [comment]
I'm working on this right now!

**Comment by genevaporter** [comment]
Done! Pull request created.

**Comment by bangerth** [comment]
@genevaporter There were 9 entries here, but didn't you only add 8 to the bibtex files?

**Comment by marcfehling** [comment]
1. > S. Shiozawa*, S. Lee, M.F. Wheeler
The effect of stress boundary conditions on fluid-driven fracture propagation in porous media using a phase field modeling approach,
2019, International Journal for Numerical and Analytical Methods in Geomechanics, DOI: 10.1002/nag.2899

https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2019.bib#L1029-L1041

2. > J.Choo*, S. Lee
Enriched Galerkin Finite Element Method for Locally Mass Conservative Simulation of Coupled Hydromechanical Problems
2018, Proceedings of China-Europe Conference on Geotehcnical Engineering, Springer Nature Switzerland AG

- [ ] **missing**

3. > J. Choo*, S.Lee
Enriched Galerkin finite elements for coupled poromechanics with local mass conservation,
2018 November, Volume 341, Pages 311-332 Computer Methods in Applied Mechanics and Engineering

https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2018.bib#L2130-L2141

4. > S. Lee*, M. F. Wheeler
Enriched Galerkin approximations for two phase flow in porous media with capillary pressure,
2018, Volume 367, 15 August 2018, Pages 65-86, https://doi.org/10.1016/j.jcp.2018.03.031, Journal of Computational Physics

https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2018.bib#L282-L293

5. > S. Lee*, A. Mikelic, M. F. Wheeler, T. Wick
Phase-field modeling of two phase fluid-filled fractures in a poroelastic medium,
2018, 16-4, pp. 1542-1580, https://doi.org/10.1137/17M1145239, SIAM Multiscale Modeling and Simulation

https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2018.bib#L806-L818

6. > S. Lee, B. Min*, M. F. Wheeler
Optimal hydraulic fracturing design using the phase field model coupled with global-objective genetic algorithm,
2018, Volume 22, Issue 3, pp 833-849, Computational Geosciences, doi:10.1007/s10596-018-9728-6

https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2018.bib#L1220-L1229

- [ ] **doi missing**

7. > Rencheng Dong*, M.F. Wheeler, S. Lee
Numerical Simulation of Matrix Acidizing in Fractured Carbonate Reservoirs Using Adaptive Enriched Galerkin Method
2019, SPE-193862-MS, SPE RSC 2019, https://doi.org/10.2118/193862-MS

https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2019.bib#L1009-L1017

8. > M.F. Wheeler*, S. Srinivasan, S. Lee, M. Singh
Unconventional Reservoir Management Modeling Coupling Diffusive Zone/Phase Field Fracture Modeling and Fracture Probability Maps,
2019, SPE 193830-MS, SPE RSC 2019, https://doi.org/10.2118/193830-MS

https://github.com/dealii/publication-list/blob/262a0b897a9008d5cc9b091ded3224f83f41004d/publications-2019.bib#L1019-L1027

9. > W. Choi, S. Lee*
Optimal Error Estimate of Elliptic Problems with Dirac Sources,
2019, submitted

- [ ] **missing**
