### ISSUE TITLE
Another paper

### ISSUE THREAD

**Issue by bangerth** [dealii/publication-list#92]
I *believe* that this paper uses deal.II, but I can't tell at the moment because I can't download it from here:
https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.5843
Someone should check and if necessary add the reference.

There may be more from this author:
https://www.researchgate.net/profile/Andrew_Lambe3

**Comment by jppelteret** [comment]
Yip

> The finite element calculations are carried out with the deal.II C++ package.18 Deal.II is an open source finite‐element library that contains a variety of functions to help construct simple meshes, define finite elements, compute integrals of interest, assemble appropriate matrices and vectors, solve linear systems, and refine meshes. Particularly useful to this study, deal.II contains an implementation of the Bernstein finite element we use to define the density field.
